language: java
sudo: false
install: true
jdk:
  - oraclejdk8
script:
  - "cd build"
  - "ant rebuild -lib ./tools/junit/"
  - "cd $TRAVIS_BUILD_DIR"
  - ./runSonarQubeAnalysis.sh

cache:
  directories:
    - '$HOME/.sonar/cache'